-- LUX — MIGRAÇÃO COMPLETA DE CONTAS, MODELOS E AVALIAÇÕES
-- Não apaga tabelas existentes. Pode ser executado no SQL Editor.

create table if not exists public.perfis (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  tipo text not null check (tipo in ('usuario','modelo','admin')),
  status text not null default 'ativo' check (status in ('ativo','pendente','aprovado','bloqueado')),
  created_at timestamptz default now()
);

alter table public.perfis enable row level security;

-- Novas informações da conta
alter table public.perfis add column if not exists updated_at timestamptz default now();

create table if not exists public.modelo_perfis (
  id uuid primary key references public.perfis(id) on delete cascade,
  nome_exibicao text not null,
  idade integer not null check (idade between 18 and 99),
  cidade text,
  pais text default 'Brasil',
  cor_cabelo text,
  cor_olhos text,
  altura_cm integer check (altura_cm between 100 and 230),
  idiomas text,
  descricao text check (char_length(coalesce(descricao,'')) <= 800),
  foto_url text,
  galeria_urls text[] default '{}',
  maioridade_confirmada boolean not null default false,
  verificacao_status text not null default 'pendente' check (verificacao_status in ('pendente','em_analise','verificada','reprovada')),
  estrelas_total integer not null default 0 check (estrelas_total >= 0),
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now()
);

create table if not exists public.avaliacoes_modelos (
  id bigint generated by default as identity primary key,
  modelo_id uuid not null references public.modelo_perfis(id) on delete cascade,
  usuario_id uuid not null references auth.users(id) on delete cascade,
  valor smallint not null default 1 check (valor = 1),
  created_at timestamptz default now(),
  unique(modelo_id, usuario_id)
);

alter table public.modelo_perfis enable row level security;
alter table public.avaliacoes_modelos enable row level security;

-- Função segura para identificar o tipo sem expor privilégios.
create or replace function public.meu_tipo()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select tipo from public.perfis where id = auth.uid();
$$;

-- Criação automática do perfil logo após o cadastro no Auth.
create or replace function public.handle_novo_usuario()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tipo text := coalesce(new.raw_user_meta_data->>'tipo','usuario');
  v_nome text := coalesce(new.raw_user_meta_data->>'nome','Usuário LUX');
begin
  if v_tipo not in ('usuario','modelo') then v_tipo := 'usuario'; end if;
  insert into public.perfis(id,nome,tipo,status)
  values(new.id,v_nome,v_tipo,case when v_tipo='modelo' then 'pendente' else 'ativo' end)
  on conflict (id) do nothing;
  if v_tipo='modelo' then
    insert into public.modelo_perfis(
      id,nome_exibicao,idade,cidade,pais,cor_cabelo,cor_olhos,altura_cm,idiomas,descricao,foto_url,maioridade_confirmada
    )
    values(
      new.id,
      v_nome,
      greatest(18, least(99, coalesce((new.raw_user_meta_data->>'idade')::integer,18))),
      nullif(new.raw_user_meta_data->>'cidade',''),
      coalesce(nullif(new.raw_user_meta_data->>'pais',''),'Brasil'),
      nullif(new.raw_user_meta_data->>'cor_cabelo',''),
      nullif(new.raw_user_meta_data->>'cor_olhos',''),
      case when (new.raw_user_meta_data->>'altura_cm') ~ '^[0-9]+$' then (new.raw_user_meta_data->>'altura_cm')::integer else null end,
      nullif(new.raw_user_meta_data->>'idiomas',''),
      left(nullif(new.raw_user_meta_data->>'descricao',''),800),
      nullif(new.raw_user_meta_data->>'foto_url',''),
      coalesce((new.raw_user_meta_data->>'maioridade_confirmada')::boolean,false)
    )
    on conflict (id) do update set
      nome_exibicao=excluded.nome_exibicao, idade=excluded.idade, cidade=excluded.cidade, pais=excluded.pais,
      cor_cabelo=excluded.cor_cabelo, cor_olhos=excluded.cor_olhos, altura_cm=excluded.altura_cm, idiomas=excluded.idiomas,
      descricao=excluded.descricao, foto_url=excluded.foto_url, maioridade_confirmada=excluded.maioridade_confirmada;
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_novo_usuario();

-- Recalcula o total de estrelas sem permitir edição manual pelo usuário.
create or replace function public.recalcular_estrelas_modelo()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.modelo_perfis mp
  set estrelas_total = (select count(*) from public.avaliacoes_modelos a where a.modelo_id = mp.id),
      atualizado_em = now()
  where mp.id = coalesce(new.modelo_id, old.modelo_id);
  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_recalcular_estrelas on public.avaliacoes_modelos;
create trigger trg_recalcular_estrelas
after insert or delete on public.avaliacoes_modelos
for each row execute function public.recalcular_estrelas_modelo();

-- Remove somente políticas com nomes deste sistema para permitir rerun.
drop policy if exists "cada usuario ve o proprio perfil" on public.perfis;
drop policy if exists "usuario cria o proprio perfil" on public.perfis;
drop policy if exists "perfil proprio select" on public.perfis;
drop policy if exists "modelo atualiza proprio perfil" on public.perfis;
drop policy if exists "modelos aprovados publicos" on public.modelo_perfis;
drop policy if exists "modelo ve proprio cadastro" on public.modelo_perfis;
drop policy if exists "modelo atualiza cadastro" on public.modelo_perfis;
drop policy if exists "admin gerencia modelos" on public.modelo_perfis;
drop policy if exists "usuario pode ver avaliacoes" on public.avaliacoes_modelos;
drop policy if exists "usuario pode avaliar uma vez" on public.avaliacoes_modelos;

create policy "perfil proprio select"
on public.perfis for select to authenticated
using (auth.uid() = id or public.meu_tipo() = 'admin');

create policy "perfil proprio update"
on public.perfis for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id and tipo in ('usuario','modelo'));

create policy "admin gerencia perfis"
on public.perfis for update to authenticated
using (public.meu_tipo() = 'admin')
with check (public.meu_tipo() = 'admin');

create policy "modelos aprovados publicos"
on public.modelo_perfis for select to anon, authenticated
using (verificacao_status = 'verificada' and (select status from public.perfis where id = modelo_perfis.id) in ('aprovado','ativo'));

create policy "modelo ve proprio cadastro"
on public.modelo_perfis for select to authenticated
using (auth.uid() = id or public.meu_tipo() = 'admin');

create policy "modelo atualiza cadastro"
on public.modelo_perfis for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id and idade >= 18 and maioridade_confirmada = true);

create policy "admin gerencia modelos"
on public.modelo_perfis for all to authenticated
using (public.meu_tipo() = 'admin')
with check (public.meu_tipo() = 'admin');

create policy "modelo cria cadastro"
on public.modelo_perfis for insert to authenticated
with check (auth.uid() = id and idade >= 18 and maioridade_confirmada = true);

create policy "usuario pode ver avaliacoes"
on public.avaliacoes_modelos for select to anon, authenticated
using (true);

create policy "usuario pode avaliar uma vez"
on public.avaliacoes_modelos for insert to authenticated
with check (auth.uid() = usuario_id and valor = 1 and exists (
  select 1 from public.perfis p where p.id = auth.uid() and p.tipo = 'usuario' and p.status = 'ativo'
) and exists (
  select 1 from public.modelo_perfis m where m.id = modelo_id and m.verificacao_status = 'verificada'
));

-- Storage para fotos de perfil. A imagem é pública somente quando o perfil for publicado.
insert into storage.buckets (id,name,public)
values ('modelos','modelos',true)
on conflict (id) do update set public = true;

drop policy if exists "modelo pode enviar foto" on storage.objects;
drop policy if exists "modelo pode atualizar foto" on storage.objects;
drop policy if exists "modelo pode apagar foto" on storage.objects;

create policy "modelo pode enviar foto"
on storage.objects for insert to authenticated
with check (bucket_id='modelos' and (storage.foldername(name))[1] = auth.uid()::text and public.meu_tipo()='modelo');

create policy "modelo pode atualizar foto"
on storage.objects for update to authenticated
using (bucket_id='modelos' and (storage.foldername(name))[1] = auth.uid()::text and public.meu_tipo()='modelo')
with check (bucket_id='modelos' and (storage.foldername(name))[1] = auth.uid()::text and public.meu_tipo()='modelo');

create policy "modelo pode apagar foto"
on storage.objects for delete to authenticated
using (bucket_id='modelos' and (storage.foldername(name))[1] = auth.uid()::text and public.meu_tipo()='modelo');

-- Sincroniza modelos antigos: cria registro básico onde faltar.
insert into public.modelo_perfis(id,nome_exibicao,idade,maioridade_confirmada)
select p.id,p.nome,18,false
from public.perfis p
where p.tipo='modelo'
on conflict (id) do nothing;


-- ============================================================
-- LUX ADVANCE — PLANOS, SELOS E PAGAMENTOS MERCADO PAGO
-- Execute esta parte depois da migração acima.
-- ============================================================
alter table public.modelo_perfis add column if not exists plano_codigo text not null default 'ESSENCE';
alter table public.modelo_perfis add column if not exists plano_nome text not null default 'LUX-ESSENCE';
alter table public.modelo_perfis add column if not exists plano_status text not null default 'ativo';
alter table public.modelo_perfis add column if not exists selo_codigo text not null default 'ESSENCE';
alter table public.modelo_perfis add column if not exists plano_inicio timestamptz;
alter table public.modelo_perfis add column if not exists plano_expira_em timestamptz;
alter table public.modelo_perfis add column if not exists mp_subscription_id text;

create table if not exists public.pagamentos_planos (
  id uuid primary key default gen_random_uuid(),
  modelo_id uuid not null references public.modelo_perfis(id) on delete cascade,
  plano_codigo text not null check (plano_codigo in ('ESSENCE','DESFIRE','ELITE','ROYAL')),
  valor numeric(10,2) not null check (valor >= 0),
  moeda text not null default 'BRL',
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled','paused')),
  mp_subscription_id text,
  mp_payment_id text,
  external_reference text unique not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.pagamentos_planos enable row level security;
drop policy if exists "modelo ve seus pagamentos" on public.pagamentos_planos;
create policy "modelo ve seus pagamentos" on public.pagamentos_planos for select to authenticated
using (modelo_id = auth.uid() or public.meu_tipo()='admin');

drop function if exists public.ativar_plano_gratuito(text);
create or replace function public.ativar_plano_gratuito(p_plano text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_plano <> 'ESSENCE' then raise exception 'Plano inválido'; end if;
  if not exists(select 1 from public.perfis where id=auth.uid() and tipo='modelo') then raise exception 'Somente modelos podem ativar planos'; end if;
  update public.modelo_perfis set plano_codigo='ESSENCE', plano_nome='LUX-ESSENCE', plano_status='ativo', selo_codigo='ESSENCE', plano_inicio=now(), plano_expira_em=null, mp_subscription_id=null, atualizado_em=now() where id=auth.uid();
end; $$;
grant execute on function public.ativar_plano_gratuito(text) to authenticated;

-- Reforça os valores públicos dos selos para que sejam exibidos no perfil publicado.
comment on column public.modelo_perfis.selo_codigo is 'Selo público do plano: ESSENCE, VERIFICADO, ELITE ou ROYAL';

-- SEGURANÇA: plano e selo são controlados pelo servidor/webhook.
-- Modelos não podem alterar manualmente benefícios premium pelo cliente.
drop trigger if exists proteger_plano_modelo on public.modelo_perfis;
create or replace function public.proteger_plano_modelo()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
begin
  if coalesce(auth.role(),'') <> 'service_role' and coalesce(public.meu_tipo(),'') <> 'admin' then
    -- O cliente pode permanecer/voltar ao plano gratuito, mas nunca
    -- pode atribuir a si mesmo VERIFICADO, ELITE ou ROYAL.
    if new.plano_codigo is distinct from old.plano_codigo
       or new.plano_nome is distinct from old.plano_nome
       or new.plano_status is distinct from old.plano_status
       or new.selo_codigo is distinct from old.selo_codigo
       or new.plano_inicio is distinct from old.plano_inicio
       or new.plano_expira_em is distinct from old.plano_expira_em
       or new.mp_subscription_id is distinct from old.mp_subscription_id then
      if not (new.plano_codigo='ESSENCE' and new.plano_nome='LUX-ESSENCE'
              and new.plano_status='ativo' and new.selo_codigo='ESSENCE'
              and new.plano_expira_em is null and new.mp_subscription_id is null) then
        raise exception 'Plano e selo são gerenciados automaticamente pelo LUX.';
      end if;
    end if;
  end if;
  return new;
end; $$;

create trigger proteger_plano_modelo
before update on public.modelo_perfis
for each row execute function public.proteger_plano_modelo();
